// <auto-generated />
using System;
using Backend.Service.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230131034743_InitializeSeedData")]
    partial class InitializeSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Service.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "",
                            CreatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2095),
                            IsDeleted = false,
                            Name = "Admin",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2094)
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "",
                            CreatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2097),
                            IsDeleted = false,
                            Name = "Staff",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2097)
                        },
                        new
                        {
                            Id = 3,
                            AddedBy = "",
                            CreatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2098),
                            IsDeleted = false,
                            Name = "Customer",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2098)
                        },
                        new
                        {
                            Id = 4,
                            AddedBy = "",
                            CreatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2099),
                            IsDeleted = false,
                            Name = "Guest",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2098)
                        });
                });

            modelBuilder.Entity("Backend.Service.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "",
                            CreatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2184),
                            Email = "admin@chystore.vn",
                            Fullname = "Admin Chystore",
                            Gender = false,
                            IsDeleted = false,
                            Password = "MTIzNDU2",
                            Phone = "0123456789",
                            RoleId = 1,
                            Status = true,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2023, 1, 31, 3, 47, 43, 742, DateTimeKind.Utc).AddTicks(2183)
                        });
                });

            modelBuilder.Entity("Backend.Service.Entities.User", b =>
                {
                    b.HasOne("Backend.Service.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Service.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
